name: Build and deploy Node.js app to Azure Web App - Competitor-avocarbon

on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install
        run: npm install
      - name: npm build
        run:  npm run build

      - name: Zip artifact for deployment
        run: zip -r release.zip build/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
  
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_97C2B1F7630544E4ABFA14CD5BD90BBD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8F9F0C4866674EFCA202CA39FB60B32C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_06DF308FB9A4485AADF94880F8713800 }}
  
      - name: Remove WEBSITE_RUN_FROM_PACKAGE if present
        run: |
          az webapp config appsettings delete \
            --name Competitor-avocarbon \
            --resource-group STS_Developments \
            --setting-names WEBSITE_RUN_FROM_PACKAGE
  
      - name: Deploy with retries using az webapp deploy
        run: |
          for i in {1..5}; do
            echo "Attempt $i to deploy..."
            az webapp deploy \
              --resource-group STS_Developments \
              --name Competitor-avocarbon \
              --src-path release.zip \
              --type zip && break || sleep 15
          done

